kind: ConfigMap
metadata:
  name: locator-config
apiVersion: v1
data:
  init.sh: |-
    #!/bin/bash
    set -e
    set -x
    [ -d /mnt/data/locator ] || mkdir /mnt/data/locator
    cp -Lur /etc/locator-configmap/* /etc/locator/
    echo "locators=${LOCATORS}"  >> /etc/locator/gemfire.properties
    
  
  gemfire.properties: |
    #Logs and stats should be ~ 5GB
    distributed-system-id=1
    log-file=locator.log
    log-disk-space-limit=4096
    log-file-size-limit=1024
    statistic-sampling-enabled=true
    statistic-archive-file=locator.gfs
    archive-file-size-limit=100
    archive-disk-space-limit=1000
    enable-time-statistics=true