apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-server-0
  labels:
    type: local
  annotations:
    geode: server
spec:
  storageClassName: geode-storage
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/k8sdata/server-0"
  capacity:
    storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-server-1
  labels:
    type: local
  annotations:
    geode: server
spec:
  storageClassName: geode-storage
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/k8sdata/server-1"
  capacity:
    storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-server-2
  labels:
    type: local
  annotations:
    geode: server
spec:
  storageClassName: geode-storage
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/k8sdata/server-2"
  capacity:
    storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-server-3
  labels:
    type: local
  annotations:
    geode: server
spec:
  storageClassName: geode-storage
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/k8sdata/server-3"
  capacity:
    storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-server-4
  labels:
    type: local
  annotations:
    geode: server
spec:
  storageClassName: geode-storage
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/k8sdata/server-4"
  capacity:
    storage: 2Gi
