apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
  # Note it was found I just need to have a port here - no need to enumerate ports
  - port: 40404
    name: client-port
  clusterIP: None
  selector:
    app: server
    storage: persistent
